# Suggested data paths when using GPT-NeoX locally
{
        #  "data-path": "HPCorpus_final/pre_train/c-cpp-polycoder/gpt2tok/allc_code_document",
  "data-path": "HPCorpus_final/pre_train/fortran/gpt2tok/fortran_code_document",
  #"data-path": "HPCorpus_final/fine_tune/fortran/gpt2tok/fortran_code_document",

  "vocab-file": "data/gpt2-vocab.json",
  "merge-file": "data/gpt2-merges.txt",

  "do_train": 0,
  "do_valid": 1,
  "do_test": 0,
  #  "split": "0,0,100",
  "load": "checkpoints/fortran_gpt2tok_160M",
  "checkpoint_validation_with_forward_pass": False,

  "tensorboard-dir": "tensorboard",
  "log-dir": "logs",
  "use_wandb": False,
}
