{
  "finetune-data-path": "lm_data/hf/",
  "data-keys-collate": ["has_bug"],
  "tokenizer-type": "GPT2BPETokenizer",
  "vocab-file": "data/gpt2-vocab.json",
  "merge-file": "data/gpt2-merges.txt",
  "save": "checkpoints/varmisuse/test",
  "load": "checkpoints/checkpoints-160M/",
  "finetune": True,
  "split": "109,11,58",
  
  "checkpoint_validation_with_forward_pass": False,

  "tensorboard-dir": "tensorboard",
  "log-dir": "logs",
  "use_wandb": False,
}
