# Suggested data paths when using GPT-NeoX locally
{
        #  "data-path": "HPCorpus_final/pre_train/c-cpp-polycoder/gpt2tok/allc_code_document",
  "data-path": "HPCorpus_final/pre_train/fortran/tokompiler/fortran_code_document",

  "tokenizer-type": "Tokompiler",
  "vocab-file": "megatron/tokenizer/tokompiler/tokenizer_vocab/vocab.txt",

  "save": "checkpoints/fortran_tokompiler_160M/hyperparams1",
  #"load": "checkpoints/fortran_gpt2tok_160M",
  #  "finetune": True,
  "checkpoint_validation_with_forward_pass": False,

  "tensorboard-dir": "tensorboard",
  "log-dir": "logs",
  "use_wandb": False,
}
